---
- hosts: all
  roles:  # Использовать роли
    - role: setting  # Роль setting
      tags: ["setting"]  # Тег для настройки системы
    
    - role: backup  # Роль backup
      tags: ["backup"]  # Тег для выполнения бэкапа
      