---
- name: creating directory or file  # Имя задачи
  ansible.builtin.include_tasks:  # Название модуля
    file: create_dir.yaml  # Аргумент модуля

- name: archiving  # Имя задачи
  ansible.builtin.include_tasks:  # Название модуля
    file: archiving.yaml  # Аргумент модуля