---
- name: set timezone  # Имя задачи
  ansible.builtin.include_tasks:  # Название модуля
    file: configure_timezone.yaml  # Аргумент модуля

- name: set crontab  # Имя задачи
  ansible.builtin.include_tasks:  # Название модуля
    file: setup_crontab.yaml  # Аргумент модуля