---
- name: set timezone  # Имя задачи
  ansible.builtin.include_tasks:  # Название модуля
    file: set_timezone.yaml  # Аргумент модуля

- name: set crontab  # Имя задачи
  ansible.builtin.include_tasks:  # Название модуля
    file: set_crontab.yaml  # Аргумент модуля

- name: set locale  # Имя задачи
  ansible.builtin.import_tasks:  # Название модуля
    file: set_locale.yaml  # Аргумент модуля
  become: true  # Запускать все модули в задаче от имени рута (root)