---
- name: set timezone  # Название задачи (настройка часового пояса)
  community.general.timezone:  # Модуль для настройки часового пояса
    name: "Europe/Moscow"  # Название часового пояса
    hwclock: UTC  # Настройка RTC (Real Time Clock) — часы, которые встроены в материнскую плату
  become: true  # Запускать задачу от имени рута (root)