
- name: archiving dir/file  # Имя задачи (архивация папки/файла)
  community.general.archive:  # Модуль для архивации 
    path: "{{ backup_src }}"  # Путь к файлу или папке которую будем архивировать
    dest: "{{ backup_dest }}/{{ time }}.tar.gz"  # Путь куда будет сохранен архив
    force_archive: true  # Архивировать даже если там всего один файл
    mode: "{{ mode_archive }}"  # Какие права будут на архив
    owner: "{{ owner_archive }}"  # Владелец архива