
- name: archiving dir/file #имя задачи (архивация папки/файла)
  community.general.archive: #модуль для архивации 
    path: "{{ backup_sr }}" #путь к файлу или папке которую будем архивировать
    dest: "{{ backup_dest }}/{{ time }}.tar.gz" #путь куда будет сохранен архив
    force_archive: true #архивировать даже если там всего один файл
    mode: "0755" #фулл права для владеьца архива, чтение и выполнение для всех остальных
    owner: "{{ owner_archive }}" #владелец архива