---
- name: create dir #имя задачи (создание папки)
  ansible.builtin.file: #модуль для создания папки в которую будет складываться архив, т.к если ее не будет, задача упадет в ошибку
    path: "{{ backup_dest }}" #путь где будет создана папка
    state: directory #создаем папку
    mode: '0755' #фулл права для владеьца папки, чтение и выполнение для всех остальных
    owner: "{{ owner_dir }}" #владелец папки
    recurse: true #рекуриснвые права на папку
