---
- name: create dir  # Имя задачи (создание папки)
  ansible.builtin.file:  # Модуль для создания папки в которую будет складываться архив, т.к если ее не будет, задача упадет в ошибку
    path: "{{ backup_dest }}"  # Путь где будет создана папка
    state: directory  # Создаем папку
    mode: "{{ mode_dir }}"  # Какие права будут на папку и файлы в ней
    owner: "{{ owner_dir }}"  # Владелец папки
