---
#переменные
backup_src: /home/sgorod/OptCheck.yaml #откуда будет делаться бэкап
backup_dest: /home/sgorod/backup #куда будет делаться бэкап
time: "{{ ansible_date_time.day }}.{{ ansible_date_time.month }}.{{ ansible_date_time.year }}:{{ ansible_date_time.hour }}.{{ ansible_date_time.minute }}.{{ ansible_date_time.second }}" #установка времени в порядке котором я захотел
owner_dir: sgorod #владелец файла/папки
owner_archive: sgorod #владелец архива
