---
# Переменные
backup_src: /home/sgorod/OptCheck.yaml  # Откуда будет делаться бэкап
backup_dest: /home/sgorod/backup  # Куда будет делаться бэкап
time: "{{ ansible_date_time.day }}.{{ ansible_date_time.month }}.{{ ansible_date_time.year }}:{{ ansible_date_time.hour }}.{{ ansible_date_time.minute }}.{{ ansible_date_time.second }}"  # Установка времени в порядке котором я захотел
owner_dir: sgorod  # Владелец файла/папки
mode_dir: '0755'  # Права на папку
owner_archive: sgorod  # Владелец архива
mode_archive: '0644'  # Права на архив
